name = "goose-joke-generator-dtw"
compatibility_date = "2024-11-11"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 7153

[[d1_databases]]
binding = "DB"
database_name = "goose-joke-generator-d1"
database_id = "8dce9440-0788-4dd1-89af-e337fde0184e"
migrations_dir = "drizzle/migrations"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "GOOSE_JOKES_CACHE"
id = "470ab99f77314494b3f624c41b452c15"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

[ai]
binding = "AI"
